#ifndef GUARD_CONSTANTS_RANDOMIZER_PICKS_H
#define GUARD_CONSTANTS_RANDOMIZER_PICKS_H

// T-236 / ADR-022 — indices into gItemPicks[] (src/randomizer_picks.c). Shared between C and the
// event scripts (plain #defines — this header is #included from data/event_scripts.s).
//
// 0..PICK_RANDOMIZED_COUNT-1 are regenerated by the randomizer between the anchors in
// src/randomizer_picks.c (randomizer/itemRandomizer.js PICK_TABLE must match this order exactly).
// Entries from PICK_RANDOMIZED_COUNT up are static TM picks (never rewritten — their menu labels
// resolve at runtime from the TM item's move).

// Menu picks (3 or 4 options — see the per-map stub for the count)
#define PICK_PETALBURG_PLATES        0
#define PICK_ROUTE104_GEMS           1
#define PICK_ROUTE104_BERRIES        2
#define PICK_ROUTE117_BERRIES        3
#define PICK_ROUTE117_GEMS           4
#define PICK_ROUTE111_BERRIES        5
#define PICK_ROUTE121_ITEMS          6
#define PICK_ROUTE111_ITEMS          7
#define PICK_ROUTE116_GEM            8
#define PICK_ROUTE116_BERRY          9
#define PICK_ROUTE118_ITEMS         10
#define PICK_ROUTE106_BALL          11
#define PICK_ROUTE102_BALL          12
#define PICK_ROUTE117_PLATE         13
#define PICK_ROUTE110_EXTENDER      14
#define PICK_ROUTE111_BALL_A        15
#define PICK_ROUTE111_BALL_C        16
#define PICK_ROUTE115_BALL          17
#define PICK_ROUTE116_BALL          18
// Single-item locations (no menu — the stub takes slot 0)
#define PICK_ROUTE106_GOOD_ITEM     19
#define PICK_ROUTE116_X_SPECIAL     20
#define PICK_ROUTE118_BARNY_GOOD    21
#define PICK_ROUTE120_ANGELICA_GOOD 22
#define PICK_ROUTE109_GOOD_ITEM     23
#define PICK_ROUTE110_GOOD_ITEM     24
#define PICK_ROUTE110_LUM           25
#define PICK_ROUTE117_EARTHQUAKE    26
#define PICK_ROUTE111_HP_UP         27
#define PICK_ROUTE114_WYATT_GOOD    28

#define PICK_RANDOMIZED_COUNT       29

// TM picks — STATIC entries (never rewritten by the randomizer): the TM slot per option is fixed,
// only the move behind the slot changes (tms_hms.h / gTMHMItemMoveIds), and the menu labels resolve
// at runtime ("TM <move>" via BufferItemPickName). Their per-option finditem handlers stay in the
// map scripts; only the menu comes from here.
#define PICK_TM_ROUTE104            29
#define PICK_TM_ROUTE104_2          30
#define PICK_TM_ROUTE106            31
#define PICK_TM_ROUTE110            32
#define PICK_TM_ROUTE114_CHARLOTTE  33
#define PICK_TM_ROUTE114_NOLAN      34
#define PICK_TM_ROUTE114_ANGELINA   35
#define PICK_TM_ROUTE111            36
#define PICK_TM_ROUTE117_SCREEN     37
#define PICK_TM_ROUTE118            38
#define PICK_TM_ROUTE118_2          39
#define PICK_TM_ROUTE118_3          40
#define PICK_TM_ROUTE120            41
#define PICK_TM_ROUTE121_2          42
#define PICK_TM_ROUTE125            43
#define PICK_TM_ROUTE112_STATUS     44
#define PICK_TM_ROUTE112_DMG        45
#define PICK_TM_ROUTE111_FOCUS      46
#define PICK_TM_ROUTE111_WILTON     47
#define PICK_TM_ROUTE121            48
#define PICK_TM_ROUTE124            49
#define PICK_TM_ROUTE109_RICKY      50
#define PICK_TM_ROUTE109_HUEY       51
#define PICK_TM_ROUTE116_ITEM       52

#define PICK_COUNT                  53

#define MAX_PICK_ITEMS 4

// T-236 — mega-trainer hide flags: gMegaTrainerHidden[] (src/randomizer_picks.c) has one entry per
// randomizer/constants.js MEGA_TRAINERS entry (index = id - 1). When set, the engine does not spawn
// that mega's trainer NPC + mega-stone ball (was: object_event deletion from map.json).
#define MEGA_TRAINER_COUNT 21

#endif // GUARD_CONSTANTS_RANDOMIZER_PICKS_H
