#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(SAND_TOMB) \
    F(INCINERATE) \
    F(ELECTROWEB) \
    F(AIR_CUTTER) \
    F(WATER_PULSE) \
    F(METAL_CLAW) \
    F(ICY_WIND) \
    F(SILVER_WIND) \
    F(TAKE_DOWN) \
    F(ACID_SPRAY) \
    F(POWER_GEM) \
    F(EGG_BOMB) \
    F(FACADE) \
    F(HEAT_CRASH) \
    F(BODY_SLAM) \
    F(EXPANDING_FORCE) \
    F(BLAST_BURN) \
    F(RETALIATE) \
    F(PSYCHO_CUT) \
    F(GRASS_KNOT) \
    F(POISON_JAB) \
    F(GIGA_DRAIN) \
    F(GRASSY_GLIDE) \
    F(SCALE_SHOT) \
    F(CROSS_POISON) \
    F(ICE_FANG) \
    F(SEISMIC_TOSS) \
    F(ACROBATICS) \
    F(BULLET_SEED) \
    F(NIGHT_SHADE) \
    F(HURRICANE) \
    F(STEEL_BEAM) \
    F(TRIPLE_AXEL) \
    F(POWER_WHIP) \
    F(DRAGON_PULSE) \
    F(SUPERCELL_SLAM) \
    F(POLLEN_PUFF) \
    F(PSYCHIC) \
    F(WILD_CHARGE) \
    F(STONE_EDGE) \
    F(ZAP_CANNON) \
    F(HEAT_WAVE) \
    F(PETAL_BLIZZARD) \
    F(AURA_SPHERE) \
    F(EARTH_POWER) \
    F(DOUBLE_EDGE) \
    F(FIRE_BLAST) \
    F(HYDRO_PUMP) \
    F(DYNAMIC_PUNCH) \
    F(SLUDGE_BOMB) \
    F(DRACO_METEOR) \
    F(U_TURN) \
    F(FLARE_BLITZ) \
    F(FLIP_TURN) \
    F(OVERHEAT) \
    F(OUTRAGE) \
    F(FLING) \
    F(HARD_PRESS) \
    F(ENDEAVOR) \
    F(EXPLOSION) \
    F(PSYCHIC_TERRAIN) \
    F(DEFENSE_CURL) \
    F(PAIN_SPLIT) \
    F(CAPTIVATE) \
    F(GRASSY_TERRAIN) \
    F(SAFEGUARD) \
    F(IMPRISON) \
    F(TORMENT) \
    F(QUASH) \
    F(WONDER_ROOM) \
    F(AGILITY) \
    F(RAIN_DANCE) \
    F(SUNNY_DAY) \
    F(SANDSTORM) \
    F(HAIL) \
    F(REFLECT) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(TRICK_ROOM) \
    F(EERIE_IMPULSE) \
    F(TRICK) \
    F(TOXIC_SPIKES) \
    F(ENDURE) \
    F(CURSE) \
    F(IRON_DEFENSE) \
    F(HAZE) \
    F(ELECTRIC_TERRAIN) \
    F(ENCORE) \
    F(DEFOG) \
    F(TAUNT) \
    F(SOFT_BOILED) \
    F(TOXIC) \
    F(AURORA_VEIL) \
    F(WILL_O_WISP) \
    F(DRAGON_DANCE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
