#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(VACUUM_WAVE) \
    F(BRUTAL_SWING) \
    F(BRINE) \
    F(HIDDEN_POWER) \
    F(ECHOED_VOICE) \
    F(CHILLING_WATER) \
    F(MEGA_PUNCH) \
    F(BREAKING_SWIPE) \
    F(UPROAR) \
    F(STEEL_WING) \
    F(BURNING_JEALOUSY) \
    F(FIRE_PLEDGE) \
    F(GIGA_IMPACT) \
    F(FLASH_CANNON) \
    F(RAZOR_SHELL) \
    F(GRASSY_GLIDE) \
    F(LUNGE) \
    F(BLAZE_KICK) \
    F(REVENGE) \
    F(ICE_SPINNER) \
    F(MUDDY_WATER) \
    F(ICE_FANG) \
    F(REVERSAL) \
    F(DUAL_WINGBEAT) \
    F(PLAY_ROUGH) \
    F(SEISMIC_TOSS) \
    F(VENOSHOCK) \
    F(BULLET_SEED) \
    F(RETALIATE) \
    F(BRICK_BREAK) \
    F(DRAIN_PUNCH) \
    F(LEECH_LIFE) \
    F(DOUBLE_EDGE) \
    F(HIGH_HORSEPOWER) \
    F(BUG_BUZZ) \
    F(STEEL_BEAM) \
    F(FROST_BREATH) \
    F(HYPER_VOICE) \
    F(FLAMETHROWER) \
    F(POLTERGEIST) \
    F(FOUL_PLAY) \
    F(BLIZZARD) \
    F(SUPERCELL_SLAM) \
    F(PSYCHIC_FANGS) \
    F(ICE_BEAM) \
    F(PHANTOM_FORCE) \
    F(GUNK_SHOT) \
    F(SOLAR_BEAM) \
    F(POLLEN_PUFF) \
    F(HURRICANE) \
    F(U_TURN) \
    F(SUPERPOWER) \
    F(OVERHEAT) \
    F(VOLT_SWITCH) \
    F(CLOSE_COMBAT) \
    F(FLARE_BLITZ) \
    F(SELF_DESTRUCT) \
    F(FOCUS_PUNCH) \
    F(EXPLOSION) \
    F(MISTY_EXPLOSION) \
    F(CHARGE) \
    F(SWAGGER) \
    F(FAKE_TEARS) \
    F(SPEED_SWAP) \
    F(CHARM) \
    F(WONDER_ROOM) \
    F(PAIN_SPLIT) \
    F(VENOM_DRENCH) \
    F(ROCK_POLISH) \
    F(SLEEP_TALK) \
    F(RAIN_DANCE) \
    F(SUNNY_DAY) \
    F(SNOWSCAPE) \
    F(HAIL) \
    F(SANDSTORM) \
    F(LIGHT_SCREEN) \
    F(REFLECT) \
    F(TAUNT) \
    F(PSYCHIC_TERRAIN) \
    F(ELECTRIC_TERRAIN) \
    F(GRASSY_TERRAIN) \
    F(CURSE) \
    F(TRICK_ROOM) \
    F(THUNDER_WAVE) \
    F(BULK_UP) \
    F(CALM_MIND) \
    F(SPIKES) \
    F(MISTY_TERRAIN) \
    F(TRICK) \
    F(PROTECT) \
    F(AURORA_VEIL) \
    F(WILL_O_WISP) \
    F(BATON_PASS) \
    F(COSMIC_POWER) \
    F(SWORDS_DANCE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
