#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(ROCK_TOMB) \
    F(STRUGGLE_BUG) \
    F(MEGA_PUNCH) \
    F(MAGICAL_LEAF) \
    F(INFESTATION) \
    F(TAKE_DOWN) \
    F(DRAGON_TAIL) \
    F(MUD_SHOT) \
    F(BUG_BITE) \
    F(TRAILBLAZE) \
    F(FACADE) \
    F(STOMPING_TANTRUM) \
    F(TRI_ATTACK) \
    F(HYDRO_CANNON) \
    F(CRUNCH) \
    F(LUNGE) \
    F(PSYCHIC_NOISE) \
    F(DARK_PULSE) \
    F(MEGA_KICK) \
    F(VENOSHOCK) \
    F(PLAY_ROUGH) \
    F(IRON_HEAD) \
    F(ALLURING_VOICE) \
    F(LASH_OUT) \
    F(BODY_SLAM) \
    F(ICE_SPINNER) \
    F(BODY_PRESS) \
    F(FIRE_PUNCH) \
    F(FIRE_FANG) \
    F(BURNING_JEALOUSY) \
    F(WILD_CHARGE) \
    F(STONE_EDGE) \
    F(SUPERCELL_SLAM) \
    F(MEGAHORN) \
    F(FLAMETHROWER) \
    F(DRAGON_PULSE) \
    F(POLTERGEIST) \
    F(ICE_BEAM) \
    F(HURRICANE) \
    F(FOUL_PLAY) \
    F(HIGH_HORSEPOWER) \
    F(FROST_BREATH) \
    F(DRAIN_PUNCH) \
    F(GUNK_SHOT) \
    F(BUG_BUZZ) \
    F(DOUBLE_EDGE) \
    F(EARTHQUAKE) \
    F(ENERGY_BALL) \
    F(SLUDGE_BOMB) \
    F(PSYCHIC_FANGS) \
    F(CLOSE_COMBAT) \
    F(FLIP_TURN) \
    F(SUPERPOWER) \
    F(LEAF_STORM) \
    F(OVERHEAT) \
    F(FLARE_BLITZ) \
    F(BEAT_UP) \
    F(HARD_PRESS) \
    F(FOCUS_PUNCH) \
    F(ENDEAVOR) \
    F(FOCUS_ENERGY) \
    F(SPEED_SWAP) \
    F(PSYCH_UP) \
    F(FAKE_TEARS) \
    F(ROCK_POLISH) \
    F(AMNESIA) \
    F(DOUBLE_TEAM) \
    F(SCARY_FACE) \
    F(FEATHER_DANCE) \
    F(SPITE) \
    F(SANDSTORM) \
    F(HAIL) \
    F(SNOWSCAPE) \
    F(RAIN_DANCE) \
    F(SUNNY_DAY) \
    F(LIGHT_SCREEN) \
    F(REFLECT) \
    F(ENCORE) \
    F(BULK_UP) \
    F(SPIKES) \
    F(TRICK) \
    F(MISTY_TERRAIN) \
    F(CALM_MIND) \
    F(TRICK_ROOM) \
    F(CURSE) \
    F(REST) \
    F(PSYCHIC_TERRAIN) \
    F(TOXIC_SPIKES) \
    F(GRASSY_TERRAIN) \
    F(ELECTRIC_TERRAIN) \
    F(AURORA_VEIL) \
    F(COSMIC_POWER) \
    F(BATON_PASS) \
    F(TAILWIND) \
    F(DRAGON_DANCE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
