gText_Birch_Welcome::
	.string "Hi! Welcome to your journey!\n"
	.string "We've already met in past games.\p"
	.string "So I'll go straight to the point.\n"
	.string "This game will skip most of the lore.\p"
	.string "In case of doubt just keep going!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Anyway, this is a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "In this journey there is level cap.\p"
	.string "Every non-boss trainer is optional,\n"
	.string "But defeating them will reward\l"
	.string "either good items or encounters.\p"
	.string "You probably want them to defeat the\n"
	.string "next boss, but it's up to you.\p"
	.string "You'll get 10 pokemon to begin your\n"
	.string "journey. Have fun with them!\p"
	.string "Also, there's an endless candy\n"
	.string "so no need to murder wild pokemon.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Anyway, who are you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Enough chit-chat. Get out of the truck\n"
	.string "and go directly to save me.\l"
	.string "Let's go!\p"
	.string "$"
