const path = require("path");

const constants = {
    TOTAL_GENS: 9,
    GENERIC_DEVIATION: 0.1,

    SPECIES_DIR: path.resolve(__dirname, '..', 'src', 'data', 'pokemon', 'species_info'),
    LEVEL_UP_LEARNSETS_DIR: path.resolve(__dirname, '..', 'src', 'data', 'pokemon', 'level_up_learnsets'),
    ABILITIES_FILE_PATH: path.resolve(__dirname, '..', 'src', 'data', 'abilities.h'),
    MEGA_EVOS_PATH: path.resolve(__dirname, '..', 'src', 'data', 'pokemon', 'form_change_tables.h'),

    TIER_BAD: 'BAD',
    TIER_WEAK: 'WEAK',
    TIER_AVERAGE: 'AVERAGE',
    TIER_STRONG: 'STRONG',
    TIER_PREMIUM: 'PREMIUM',
    TIER_LEGEND: 'LEGEND',
    TIER_GOD: 'GOD',

    TIER_GOD_THRESHOLD: 9.5,
    TIER_LEGEND_THRESHOLD: 9,
    MID_TIER_PREMIUM_THRESHOLD: 8.5,
    TIER_PREMIUM_THRESHOLD: 8,
    MID_TIER_STRONG_THRESHOLD: 7.5,
    TIER_STRONG_THRESHOLD: 7,
    MID_TIER_AVERAGE_THRESHOLD: 6.5,
    TIER_AVERAGE_THRESHOLD: 6,
    TIER_WEAK_THRESHOLD: 5,
    TIER_BAD_THRESHOLD: 3,

    GOD_BST_THRESHOLD: 710,
    LEGEND_BST_THRESHOLD: 660,
    PREMIUM_BST_THRESHOLD: 600,
    STRONG_BST_THRESHOLD: 540,
    AVERAGE_BST_THRESHOLD: 480,
    WEAK_BST_THRESHOLD: 400,

    EVO_TYPE_LC_OF_3: 'EVO_TYPE_LC_OF_3',
    EVO_TYPE_LC_OF_2: 'EVO_TYPE_LC_OF_2',
    EVO_TYPE_NFE_OF_3: 'EVO_TYPE_NFE_OF_3',
    EVO_TYPE_LAST_OF_3: 'EVO_TYPE_LAST_OF_3',
    EVO_TYPE_LAST_OF_2: 'EVO_TYPE_LAST_OF_2',
    EVO_TYPE_LC: 'EVO_TYPE_LC',
    EVO_TYPE_NFE: 'EVO_TYPE_NFE',
    EVO_TYPE_SOLO: 'EVO_TYPE_SOLO',
    EVO_TYPE_MEGA: 'EVO_TYPE_MEGA',
    EVO_TYPE_FINAL: 'EVO_TYPE_FINAL',

    ENCOUNTER_TYPE_LAND: 'ENCOUNTER_TYPE_LAND',
    ENCOUNTER_TYPE_FISH_OLD: 'ENCOUNTER_TYPE_FISH_OLD',
    ENCOUNTER_TYPE_FISH_GOOD: 'ENCOUNTER_TYPE_FISH_GOOD',
    ENCOUNTER_TYPE_WATER: 'ENCOUNTER_TYPE_WATER',
    ENCOUNTER_TYPE_FISH_SUPER: 'ENCOUNTER_TYPE_FISH_SUPER',
    ENCOUNTER_TYPE_SPECIAL: 'ENCOUNTER_TYPE_SPECIAL',

    TRAINER_POKE_STARTER_TREECKO: 'TRAINER_POKE_STARTER_TREECKO',
    TRAINER_POKE_STARTER_TORCHIC: 'TRAINER_POKE_STARTER_TORCHIC',
    TRAINER_POKE_STARTER_MUDKIP: 'TRAINER_POKE_STARTER_MUDKIP',
    TRAINER_POKE_ENCOUNTER: 'TRAINER_POKE_ENCOUNTER',
    TRAINER_REPEAT_ID: 'TRAINER_REPEAT_ID',
    TRAINER_POKE_MEGA_FROM_STONE: 'TRAINER_POKE_MEGA_FROM_STONE',

    TRAINER_RESTRICTION_NO_REPEATED_TYPE: 'TRAINER_RESTRICTION_NO_REPEATED_TYPE',
    TRAINER_RESTRICTION_ALLOW_ONLY_TYPES: 'TRAINER_RESTRICTION_ALLOW_ONLY_TYPES',
    TRAINER_RESTRICTION_ALLOW_ONLY_ABILITIES: 'TRAINER_RESTRICTION_ALLOW_ONLY_ABILITIES',
    TRAINER_RESTRICTION_MUST_LEARN_TM_MOVES: 'TRAINER_RESTRICTION_MUST_LEARN_TM_MOVES',
    TRAINER_E4_KEEP_TYPE_AMOUNT: 2,
    TRAINER_GYM_LEADERS_KEEP_TYPE_AMOUNT: 6,

    POKEMON_TYPE_WATER: 'WATER',
    POKEMON_TYPE_ICE: 'ICE',
    POKEMON_TYPE_BUG: 'BUG',
    POKEMON_TYPE_FAIRY: 'FAIRY',
    POKEMON_TYPE_GRASS: 'GRASS',
    POKEMON_TYPE_FIGHTING: 'FIGHTING',
    POKEMON_TYPE_PSYCHIC: 'PSYCHIC',
    POKEMON_TYPE_DARK: 'DARK',
    POKEMON_TYPE_FIRE: 'FIRE',
    POKEMON_TYPE_GROUND: 'GROUND',
    POKEMON_TYPE_ROCK: 'ROCK',
    POKEMON_TYPE_FLYING: 'FLYING',
    POKEMON_TYPE_NORMAL: 'NORMAL',
    POKEMON_TYPE_GHOST: 'GHOST',
    POKEMON_TYPE_POISON: 'POISON',
    POKEMON_TYPE_STEEL: 'STEEL',
    POKEMON_TYPE_DRAGON: 'DRAGON',
    POKEMON_TYPE_ELECTRIC: 'ELECTRIC',

    NATURES: {
        ADAMANT: {
            name: 'Adamant',
            up: 'baseAttack',
            down: 'baseSpecialAttack',
        },
        JOLLY: {
            name: 'Jolly',
            up: 'baseSpeed',
            down: 'baseSpecialAttack',
        },
        MODEST: {
            name: 'Modest',
            up: 'baseSpecialAttack',
            down: 'baseAttack',
        },
        TIMID: {
            name: 'Timid',
            up: 'baseSpeed',
            down: 'baseAttack',
        },
        BOLD: {
            name: 'Bold',
            up: 'baseDefense',
            down: 'baseAttack',
        },
        IMPISH: {
            name: 'Impish',
            up: 'baseDefense',
            down: 'baseSpecialAttack',
        },
        CALM: {
            name: 'Calm',
            up: 'baseSpecialDefense',
            down: 'baseAttack',
        },
        CAREFUL: {
            name: 'Careful',
            up: 'baseSpecialDefense',
            down: 'baseSpecialAttack',
        },
        RELAXED: {
            name: 'Relaxed',
            up: 'baseDefense',
            down: 'baseSpeed',
        },
        SASSY: {
            name: 'Sassy',
            up: 'baseSpecialDefense',
            down: 'baseSpeed',
        },
        LONELY: {
            name: 'Lonely',
            up: 'baseAttack',
            down: 'baseDefense',
        },
        NAUGHTY: {
            name: 'Naughty',
            up: 'baseAttack',
            down: 'baseSpecialDefense',
        },
        BRAVE: {
            name: 'Brave',
            up: 'baseAttack',
            down: 'baseSpeed',
        },
        LAX: {
            name: 'Lax',
            up: 'baseDefense',
            down: 'baseSpecialDefense',
        },
        MILD: {
            name: 'Mild',
            up: 'baseSpecialAttack',
            down: 'baseDefense',
        },
        RASH: {
            name: 'Rash',
            up: 'baseSpecialAttack',
            down: 'baseSpecialDefense',
        },
        QUIET: {
            name: 'Quiet',
            up: 'baseSpecialAttack',
            down: 'baseSpeed',
        },
        GENTLE: {
            name: 'Gentle',
            up: 'baseSpecialDefense',
            down: 'baseDefense',
        },
        HASTY: {
            name: 'Hasty',
            up: 'baseSpeed',
            down: 'baseDefense',
        },
        NAIVE: {
            name: 'Naive',
            up: 'baseSpeed',
            down: 'baseSpecialDefense',
        },
        QUIRKY: {
            name: 'Quirky',
            up: null,
            down: null,
        },
    },

    OUTPUT_DIR: 'output',
    TEMPLATE_FILE: 'template.html',

    TEMPLATE_POKEMON_REPLACEMENT: '<script src="pokes.js"></script>',
    TEMPLATE_MOVES_REPLACEMENT: '<script src="moves.js"></script>',
    TEMPLATE_ABILITIES_REPLACEMENT: '<script src="abilities.js"></script>',
    TEMPLATE_TRAINERS_REPLACEMENT: '<script src="trainers.js"></script>',
    TEMPLATE_WILDPOKES_REPALCEMENT: '<script src="wildpokes.js"></script>',

    LOG_TYPE_BUFF: 'BUFF',
    LOG_TYPE_NERF: 'NERF',
    LOG_TYPE_ADJUSTMENT: 'ADJUSTMENT',

    POKE_FORM_ALOLA: 'ALOLA',
    POKE_FORM_GALAR: 'GALAR',
    POKE_FORM_HISUI: 'HISUI',
    POKE_FORM_PALDEA: 'PALDEA',
    POKE_FORM_EAST: 'EAST',
    POKE_FORM_SUMMER: 'SUMMER',
    POKE_FORM_AUTUMN: 'AUTUMN',
    POKE_FORM_WINTER: 'WINTER',
    POKE_FORM_SMALL: 'SMALL',
    POKE_FORM_LARGE: 'LARGE',
    POKE_FORM_SUPER: 'SUPER',
    POKE_FORM_OWN_TEMPO: 'OWN_TEMPO',
    POKE_FORM_ANTIQUE: 'ANTIQUE',
    POKE_FORM_ROAMING: 'ROAMING',
    POKE_FORM_ARTISAN: 'ARTISAN',

    MEGA_TRAINERS: [
        {
            id: '01',
            map: 'Route111',
            trainer: 'TRAINER_TYRON',
            script: 'Route111_EventScript_Tyron',
        },
        {
            id: '02',
            map: 'JaggedPass',
            trainer: 'TRAINER_AUTUMN',
            script: 'JaggedPass_EventScript_Autumn',
        },
    ],
};

constants.POKEMON_TYPES = [
    constants.POKEMON_TYPE_WATER,
    constants.POKEMON_TYPE_ICE,
    constants.POKEMON_TYPE_BUG,
    constants.POKEMON_TYPE_FAIRY,
    constants.POKEMON_TYPE_GRASS,
    constants.POKEMON_TYPE_FIGHTING,
    constants.POKEMON_TYPE_PSYCHIC,
    constants.POKEMON_TYPE_DARK,
    constants.POKEMON_TYPE_FIRE,
    constants.POKEMON_TYPE_GROUND,
    constants.POKEMON_TYPE_ROCK,
    constants.POKEMON_TYPE_FLYING,
    constants.POKEMON_TYPE_NORMAL,
    constants.POKEMON_TYPE_GHOST,
    constants.POKEMON_TYPE_POISON,
    constants.POKEMON_TYPE_STEEL,
    constants.POKEMON_TYPE_DRAGON,
    constants.POKEMON_TYPE_ELECTRIC,
];

constants.POKE_FORMS = [
    constants.POKE_FORM_ALOLA,
    constants.POKE_FORM_GALAR,
    constants.POKE_FORM_HISUI,
    constants.POKE_FORM_PALDEA,
    constants.POKE_FORM_EAST,
    constants.POKE_FORM_SUMMER,
    constants.POKE_FORM_AUTUMN,
    constants.POKE_FORM_WINTER,
    constants.POKE_FORM_SMALL,
    constants.POKE_FORM_LARGE,
    constants.POKE_FORM_SUPER,
    constants.POKE_FORM_OWN_TEMPO,
    constants.POKE_FORM_ANTIQUE,
    constants.POKE_FORM_ROAMING,
    constants.POKE_FORM_ARTISAN,
];

module.exports = constants;