const items = {
    // Randomized items - mints
    strongAtkMints: [
        'ITEM_ADAMANT_MINT',
        'ITEM_JOLLY_MINT',
        'ITEM_MODEST_MINT',
        'ITEM_TIMID_MINT',
    ],
    strongDefMints: [
        'ITEM_BOLD_MINT',
        'ITEM_IMPISH_MINT',
        'ITEM_CALM_MINT',
        'ITEM_CAREFUL_MINT',
        'ITEM_RELAXED_MINT',
        'ITEM_SASSY_MINT',
    ],
    midMints: [
        'ITEM_LONELY_MINT',
        'ITEM_NAUGHTY_MINT',
        'ITEM_BRAVE_MINT',
        'ITEM_LAX_MINT',
        'ITEM_MILD_MINT',
        'ITEM_RASH_MINT',
        'ITEM_QUIET_MINT',
        'ITEM_GENTLE_MINT',
        'ITEM_HASTY_MINT',
        'ITEM_NAIVE_MINT',
    ],

    shards: ['ITEM_RED_SHARD', 'ITEM_BLUE_SHARD', 'ITEM_YELLOW_SHARD', 'ITEM_GREEN_SHARD'],

    fossils: [
        'ITEM_HELIX_FOSSIL',
        'ITEM_DOME_FOSSIL',
        'ITEM_OLD_AMBER',
        'ITEM_ROOT_FOSSIL',
        'ITEM_CLAW_FOSSIL',
        'ITEM_ARMOR_FOSSIL',
        'ITEM_SKULL_FOSSIL',
        'ITEM_COVER_FOSSIL',
        'ITEM_PLUME_FOSSIL',
        'ITEM_JAW_FOSSIL',
        'ITEM_SAIL_FOSSIL',
    ],

    plates: {
        ITEM_FLAME_PLATE: 'FIRE',
        ITEM_SPLASH_PLATE: 'WATER',
        ITEM_ZAP_PLATE: 'ELECTRIC',
        ITEM_MEADOW_PLATE: 'GRASS', // Petalburg Woods
        ITEM_ICICLE_PLATE: 'ICE',
        ITEM_FIST_PLATE: 'FIGHTING',
        ITEM_TOXIC_PLATE: 'POISON',
        ITEM_EARTH_PLATE: 'GROUND',
        ITEM_SKY_PLATE: 'FLYING',
        ITEM_MIND_PLATE: 'PSYCHIC',
        ITEM_INSECT_PLATE: 'BUG',
        ITEM_STONE_PLATE: 'ROCK',
        ITEM_SPOOKY_PLATE: 'GHOST',
        ITEM_DRACO_PLATE: 'DRAGON',
        ITEM_DREAD_PLATE: 'DARK',
        ITEM_IRON_PLATE: 'STEEL',
        ITEM_PIXIE_PLATE: 'FAIRY',
    },

    memories: [
        'ITEM_FIRE_MEMORY',
        'ITEM_WATER_MEMORY',
        'ITEM_ELECTRIC_MEMORY',
        'ITEM_GRASS_MEMORY',
        'ITEM_ICE_MEMORY',
        'ITEM_FIGHTING_MEMORY',
        'ITEM_POISON_MEMORY',
        'ITEM_GROUND_MEMORY',
        'ITEM_FLYING_MEMORY',
        'ITEM_PSYCHIC_MEMORY',
        'ITEM_BUG_MEMORY',
        'ITEM_ROCK_MEMORY',
        'ITEM_GHOST_MEMORY',
        'ITEM_DRAGON_MEMORY',
        'ITEM_DARK_MEMORY',
        'ITEM_STEEL_MEMORY',
        'ITEM_FAIRY_MEMORY',
    ],

    gems: [
        'ITEM_NORMAL_GEM',
        'ITEM_FIRE_GEM',
        'ITEM_WATER_GEM', // Route103
        'ITEM_ELECTRIC_GEM',
        'ITEM_GRASS_GEM',
        'ITEM_ICE_GEM',
        'ITEM_FIGHTING_GEM',
        'ITEM_POISON_GEM',
        'ITEM_GROUND_GEM',
        'ITEM_FLYING_GEM',
        'ITEM_PSYCHIC_GEM',
        'ITEM_BUG_GEM',
        'ITEM_ROCK_GEM',
        'ITEM_GHOST_GEM',
        'ITEM_DRAGON_GEM',
        'ITEM_DARK_GEM',
        'ITEM_STEEL_GEM',
        'ITEM_FAIRY_GEM',
    ],

    specifics: {
        P_FAMILY_PIKACHU: ['ITEM_LIGHT_BALL'],
        P_FAMILY_FARFETCHD: ['ITEM_LEEK'],
        P_FAMILY_CUBONE: ['ITEM_THICK_CLUB'],
        P_FAMILY_CHANSEY: ['ITEM_LUCKY_PUNCH'],
        P_FAMILY_DITTO: ['ITEM_QUICK_POWDER'],
        P_FAMILY_CLAMPERL: ['ITEM_DEEP_SEA_TOOTH', 'ITEM_DEEP_SEA_SCALE'],
        P_FAMILY_ROTOM: ['ITEM_ROTOM_CATALOG'],
        P_FAMILY_SHAYMIN: ['ITEM_GRACIDEA', 'ITEM_REVEAL_GLASS'],
        // Will I use these?
        P_FAMILY_LATIAS: ['ITEM_SOUL_DEW'],
        P_FAMILY_LATIOS: ['ITEM_SOUL_DEW'],
        P_FAMILY_DIALGA: ['ITEM_ADAMANT_ORB', 'ITEM_ADAMANT_CRYSTAL'],
        P_FAMILY_PALKIA: ['ITEM_LUSTROUS_ORB', 'ITEM_LUSTROUS_GLOBE'],
        P_FAMILY_GIRATINA: ['ITEM_GRISEOUS_ORB', 'ITEM_GRISEOUS_CORE'],
        P_FAMILY_KYUREM: ['ITEM_DNA_SPLICERS'],
        P_FAMILY_ZYGARDE: ['ITEM_ZYGARDE_CUBE'],
        P_FAMILY_HOOPA: ['ITEM_PRISON_BOTTLE'],
        P_FAMILY_NECROZMA: ['ITEM_N_SOLARIZER', 'ITEM_N_LUNARIZER'],
        P_FAMILY_CALYREX: ['ITEM_REINS_OF_UNITY'],
    },

    tms: [
        'ITEM_TM_FOCUS_PUNCH',
        'ITEM_TM_DRAGON_CLAW',
        'ITEM_TM_WATER_PULSE',
        'ITEM_TM_CALM_MIND',
        'ITEM_TM_ROAR',
        'ITEM_TM_TOXIC',
        'ITEM_TM_HAIL',
        'ITEM_TM_BULK_UP',
        'ITEM_TM_BULLET_SEED',
        'ITEM_TM_HIDDEN_POWER',
        'ITEM_TM_SUNNY_DAY',
        'ITEM_TM_TAUNT',
        'ITEM_TM_ICE_BEAM',
        'ITEM_TM_BLIZZARD',
        'ITEM_TM_HYPER_BEAM',
        'ITEM_TM_LIGHT_SCREEN',
        'ITEM_TM_PROTECT',
        'ITEM_TM_RAIN_DANCE',
        'ITEM_TM_GIGA_DRAIN',
        'ITEM_TM_SAFEGUARD',
        'ITEM_TM_FRUSTRATION',
        'ITEM_TM_SOLAR_BEAM',
        'ITEM_TM_IRON_TAIL',
        'ITEM_TM_THUNDERBOLT',
        'ITEM_TM_THUNDER',
        'ITEM_TM_EARTHQUAKE',
        'ITEM_TM_RETURN',
        'ITEM_TM_DIG',
        'ITEM_TM_PSYCHIC',
        'ITEM_TM_SHADOW_BALL',
        'ITEM_TM_BRICK_BREAK',
        'ITEM_TM_DOUBLE_TEAM',
        'ITEM_TM_REFLECT',
        'ITEM_TM_SHOCK_WAVE',
        'ITEM_TM_FLAMETHROWER',
        'ITEM_TM_SLUDGE_BOMB',
        'ITEM_TM_SANDSTORM',
        'ITEM_TM_FIRE_BLAST',
        'ITEM_TM_ROCK_TOMB',
        'ITEM_TM_AERIAL_ACE',
        'ITEM_TM_TORMENT',
        'ITEM_TM_FACADE',
        'ITEM_TM_SECRET_POWER',
        'ITEM_TM_REST',
        'ITEM_TM_ATTRACT',
        'ITEM_TM_THIEF',
        'ITEM_TM_STEEL_WING',
        'ITEM_TM_SKILL_SWAP',
        'ITEM_TM_SNATCH',
        'ITEM_TM_OVERHEAT',
    ],
    
    // Can I use these?
    tmsExtended: [
        'ITEM_TM51',
        'ITEM_TM52',
        'ITEM_TM53',
        'ITEM_TM54',
        'ITEM_TM55',
        'ITEM_TM56',
        'ITEM_TM57',
        'ITEM_TM58',
        'ITEM_TM59',
        'ITEM_TM60',
        'ITEM_TM61',
        'ITEM_TM62',
        'ITEM_TM63',
        'ITEM_TM64',
        'ITEM_TM65',
        'ITEM_TM66',
        'ITEM_TM67',
        'ITEM_TM68',
        'ITEM_TM69',
        'ITEM_TM70',
        'ITEM_TM71',
        'ITEM_TM72',
        'ITEM_TM73',
        'ITEM_TM74',
        'ITEM_TM75',
        'ITEM_TM76',
        'ITEM_TM77',
        'ITEM_TM78',
        'ITEM_TM79',
        'ITEM_TM80',
        'ITEM_TM81',
        'ITEM_TM82',
        'ITEM_TM83',
        'ITEM_TM84',
        'ITEM_TM85',
        'ITEM_TM86',
        'ITEM_TM87',
        'ITEM_TM88',
        'ITEM_TM89',
        'ITEM_TM90',
        'ITEM_TM91',
        'ITEM_TM92',
        'ITEM_TM93',
        'ITEM_TM94',
        'ITEM_TM95',
        'ITEM_TM96',
        'ITEM_TM97',
        'ITEM_TM98',
        'ITEM_TM99',
        'ITEM_TM100',
    ],

    // Probably wont use them
    specialFossils: [
        'ITEM_FOSSILIZED_BIRD',
        'ITEM_FOSSILIZED_FISH',
        'ITEM_FOSSILIZED_DRAKE',
        'ITEM_FOSSILIZED_DINO',
    ],

    // These are valuable consumables that will not be randomized
    consumables: {
        // Hidden ability
        ITEM_ABILITY_PATCH: {
            count: 3
        },
        // Normal ability
        ITEM_ABILITY_CAPSULE: {
            count: 6
        },
        ITEM_HEART_SCALE: {
            count: 10
        },
    },

    // Probably not randomized
    drives: ['ITEM_DOUSE_DRIVE', 'ITEM_SHOCK_DRIVE', 'ITEM_BURN_DRIVE', 'ITEM_CHILL_DRIVE'],

    // Probably not randomized
    premiumItems: [
        'ITEM_CHOICE_BAND',
        'ITEM_CHOICE_SPECS',
        'ITEM_CHOICE_SCARF',
        'ITEM_LEFTOVERS',
        'ITEM_LIFE_ORB',
        'ITEM_EVIOLITE', // Route103
        'ITEM_ASSAULT_VEST',
    ],

    goodItems: [
        'ITEM_SHELL_BELL',
        'ITEM_ROCKY_HELMET',
        'ITEM_SAFETY_GOGGLES',
        'ITEM_HEAVY_DUTY_BOOTS', // Route103
        'ITEM_BERSERK_GENE',
    ],

    goodSituationalItems: [
        'ITEM_FLAME_ORB',
        'ITEM_TOXIC_ORB',
        'ITEM_DAMP_ROCK',
        'ITEM_HEAT_ROCK',
        'ITEM_SMOOTH_ROCK',
        'ITEM_ICY_ROCK',
        'ITEM_WIDE_LENS',
        'ITEM_EXPERT_BELT', // Route102
        'ITEM_LIGHT_CLAY',
        'ITEM_ZOOM_LENS',
        'ITEM_BLACK_SLUDGE',
        'ITEM_SHED_SHELL',
        'ITEM_BIG_ROOT',
        'ITEM_TERRAIN_EXTENDER',
        'ITEM_PUNCHING_GLOVE',
        'ITEM_LOADED_DICE',
    ],

    goodConsumables: [
        'ITEM_WHITE_HERB',
        'ITEM_KINGS_ROCK',
        'ITEM_POWER_HERB',
        'ITEM_FOCUS_SASH',
        'ITEM_AIR_BALLOON',
        'ITEM_RED_CARD',
        'ITEM_EJECT_BUTTON',
        'ITEM_WEAKNESS_POLICY',
        'ITEM_ADRENALINE_ORB',
        'ITEM_ELECTRIC_SEED',
        'ITEM_PSYCHIC_SEED',
        'ITEM_MISTY_SEED',
        'ITEM_GRASSY_SEED',
        'ITEM_THROAT_SPRAY',
        'ITEM_EJECT_PACK',
        'ITEM_ROOM_SERVICE',
        'ITEM_LEPPA_BERRY',
        'ITEM_LUM_BERRY',
        'ITEM_SITRUS_BERRY',
        'ITEM_CUSTAP_BERRY',
        'ITEM_JABOCA_BERRY',
        'ITEM_ROWAP_BERRY',
        'ITEM_KEE_BERRY',
        'ITEM_MARANGA_BERRY',
        'ITEM_BOOSTER_ENERGY',
        'ITEM_MASTER_BALL',
    ],

    midConsumables: [
        'ITEM_LIECHI_BERRY',
        'ITEM_GANLON_BERRY',
        'ITEM_SALAC_BERRY',
        'ITEM_PETAYA_BERRY',
        'ITEM_APICOT_BERRY',
        'ITEM_LANSAT_BERRY',
        'ITEM_STARF_BERRY',
        'ITEM_ENIGMA_BERRY',
        'ITEM_MICLE_BERRY',
        'ITEM_MIRROR_HERB',
    ],

    protectionBerries: {
        NORMAL: 'ITEM_CHILAN_BERRY',
        FIRE: 'ITEM_OCCA_BERRY',
        WATER: 'ITEM_PASSHO_BERRY',
        ELECTRIC: 'ITEM_WACAN_BERRY',
        GRASS: 'ITEM_RINDO_BERRY',
        ICE: 'ITEM_YACHE_BERRY',
        FIGHTING: 'ITEM_CHOPLE_BERRY',
        POISON: 'ITEM_KEBIA_BERRY',
        GROUND: 'ITEM_SHUCA_BERRY',
        FLYING: 'ITEM_COBA_BERRY',
        PSYCHIC: 'ITEM_PAYAPA_BERRY',
        BUG: 'ITEM_TANGA_BERRY',
        ROCK: 'ITEM_CHARTI_BERRY',
        GHOST: 'ITEM_KASIB_BERRY',
        DRAGON: 'ITEM_HABAN_BERRY',
        DARK: 'ITEM_COLBUR_BERRY',
        STEEL: 'ITEM_BABIRI_BERRY',
        FAIRY: 'ITEM_ROSELI_BERRY',
    },

    midItems: [
        'ITEM_ABSORB_BULB',
        'ITEM_CELL_BATTERY',
        'ITEM_LUMINOUS_MOSS',
        'ITEM_SNOWBALL',
        'ITEM_BRIGHT_POWDER',
        'ITEM_QUICK_CLAW',
        'ITEM_SCOPE_LENS',
        'ITEM_MUSCLE_BAND',
        'ITEM_WISE_GLASSES',
        'ITEM_METRONOME',
        'ITEM_IRON_BALL',
        'ITEM_GRIP_CLAW',
        'ITEM_STICKY_BARB',
        'ITEM_FLOAT_STONE',
        'ITEM_BINDING_BAND',
        'ITEM_PROTECTIVE_PADS',
        'ITEM_UTILITY_UMBRELLA',
        'ITEM_CLEAR_AMULET',
        'ITEM_COVERT_CLOAK',
    ],

    weakConsumables: [
        'ITEM_FOCUS_BAND',
        'ITEM_MENTAL_HERB',
        'ITEM_BLUNDER_POLICY',
        'ITEM_CHERI_BERRY',
        'ITEM_CHESTO_BERRY',
        'ITEM_PECHA_BERRY',
        'ITEM_RAWST_BERRY',
        'ITEM_ASPEAR_BERRY',
        'ITEM_ORAN_BERRY',
        'ITEM_PERSIM_BERRY',
    ],

}