#!/usr/bin/env node
/**
 * check-tracker.mjs — validates the task/bug tracker and (re)generates the INDEX.md caches.
 *
 *   node scripts/check-tracker.mjs            # validate; fails (exit 1) on violations or stale indexes
 *   node scripts/check-tracker.mjs --write    # validate and regenerate tasks/INDEX.md and bugs/INDEX.md
 *
 * Task/bug files are the source of truth; INDEX.md files are generated caches.
 * Zero dependencies. Part of the Brooktec Base template.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const WRITE = process.argv.includes('--write');
const errors = [];

const TASK_STATUSES = ['proposed', 'in-progress', 'done', 'abandoned'];
const BUG_STATUSES = ['open', 'fixing', 'fixed', 'wont-fix'];
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const SEMVER_RE = /^\d+\.\d+\.\d+$/;

function parseFrontmatter(file, raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!match) {
    errors.push(`${file}: missing YAML frontmatter`);
    return {};
  }
  const data = {};
  for (const line of match[1].split('\n')) {
    const m = line.match(/^([a-z-]+):\s*(.*?)\s*(#.*)?$/);
    if (m) data[m[1]] = m[2].trim();
  }
  return data;
}

function loadEntries(dir, kind) {
  const dirPath = join(ROOT, dir);
  if (!existsSync(dirPath)) return [];
  return readdirSync(dirPath)
    .filter((f) => f.endsWith('.md') && !['TEMPLATE.md', 'INDEX.md'].includes(f))
    .map((f) => {
      const file = `${dir}/${f}`;
      const fm = parseFrontmatter(file, readFileSync(join(dirPath, f), 'utf8'));
      const idFromName = f.match(kind === 'task' ? /^(T-\d+)/ : /^(B-\d+)/)?.[1];
      if (!idFromName) errors.push(`${file}: filename must start with ${kind === 'task' ? 'T-NNN' : 'B-NNN'}`);
      if (idFromName && fm.id !== idFromName) errors.push(`${file}: frontmatter id "${fm.id}" does not match filename id "${idFromName}"`);
      return { file, ...fm };
    })
    .sort((a, b) => (a.id || '').localeCompare(b.id || '', 'en', { numeric: true }));
}

function checkCommon(e, statuses) {
  if (!statuses.includes(e.status)) errors.push(`${e.file}: invalid status "${e.status}" (expected: ${statuses.join(' | ')})`);
  for (const field of ['created', 'updated']) {
    if (!DATE_RE.test(e[field] || '')) errors.push(`${e.file}: "${field}" must be YYYY-MM-DD`);
  }
  if (!e.title) errors.push(`${e.file}: missing title`);
}

function checkDuplicates(entries, label) {
  const seen = new Map();
  for (const e of entries) {
    if (seen.has(e.id)) errors.push(`duplicate ${label} id ${e.id}: ${seen.get(e.id)} and ${e.file}`);
    seen.set(e.id, e.file);
  }
}

// --- Tasks ---
const tasks = loadEntries('tasks', 'task');
checkDuplicates(tasks, 'task');
for (const t of tasks) {
  checkCommon(t, TASK_STATUSES);
  if (!SEMVER_RE.test(t['target-version'] || '')) errors.push(`${t.file}: "target-version" must be X.Y.Z`);
}

// --- Bugs ---
const bugs = loadEntries('bugs', 'bug');
checkDuplicates(bugs, 'bug');
for (const b of bugs) {
  checkCommon(b, BUG_STATUSES);
  if (b.status === 'fixed') {
    if (!b['regression-test']) {
      errors.push(`${b.file}: status is "fixed" but "regression-test" is empty — a bug is only fixed with a regression test`);
    } else {
      const testPath = b['regression-test'].split(/[#:]/)[0].trim();
      if (!existsSync(join(ROOT, testPath))) errors.push(`${b.file}: regression-test path not found: ${testPath}`);
    }
    if (!SEMVER_RE.test(b['fixed-in'] || '')) errors.push(`${b.file}: status is "fixed" but "fixed-in" is not set`);
  }
}

// --- Changelog ---
// This is a fork of upstream pokeemerald-expansion, whose own CHANGELOG.md is the
// game's version history. Brooktec project versioning lives in CHANGELOG.brooktec.md.
if (existsSync(join(ROOT, 'CHANGELOG.brooktec.md'))) {
  const changelog = readFileSync(join(ROOT, 'CHANGELOG.brooktec.md'), 'utf8');
  if (!changelog.includes('## [Unreleased]')) errors.push('CHANGELOG.brooktec.md: missing "## [Unreleased]" section');
} else {
  errors.push('CHANGELOG.brooktec.md not found');
}

// --- Generated indexes ---
function renderIndex(entries, label, columns) {
  const header = `# ${label} index\n\n<!-- GENERATED by scripts/check-tracker.mjs — do not edit by hand. Run with --write to regenerate. -->\n`;
  if (entries.length === 0) return `${header}\n_No entries yet._\n`;
  const head = `| ${columns.map((c) => c.title).join(' | ')} |`;
  const sep = `|${columns.map(() => '---').join('|')}|`;
  const rows = entries.map((e) => `| ${columns.map((c) => c.value(e)).join(' | ')} |`);
  return `${header}\n${head}\n${sep}\n${rows.join('\n')}\n`;
}

const indexes = [
  {
    path: 'tasks/INDEX.md',
    content: renderIndex(tasks, 'Tasks', [
      { title: 'Id', value: (e) => `[${e.id}](${e.file.replace('tasks/', '')})` },
      { title: 'Title', value: (e) => e.title || '' },
      { title: 'Status', value: (e) => e.status || '' },
      { title: 'Version', value: (e) => e['target-version'] || '' },
      { title: 'Updated', value: (e) => e.updated || '' },
    ]),
  },
  {
    path: 'bugs/INDEX.md',
    content: renderIndex(bugs, 'Bugs', [
      { title: 'Id', value: (e) => `[${e.id}](${e.file.replace('bugs/', '')})` },
      { title: 'Title', value: (e) => e.title || '' },
      { title: 'Status', value: (e) => e.status || '' },
      { title: 'Severity', value: (e) => e.severity || '' },
      { title: 'Found in', value: (e) => e['found-in'] || '' },
      { title: 'Fixed in', value: (e) => e['fixed-in'] || '' },
      { title: 'Regression test', value: (e) => e['regression-test'] || '' },
    ]),
  },
];

for (const { path, content } of indexes) {
  const full = join(ROOT, path);
  if (WRITE) {
    writeFileSync(full, content);
    console.log(`wrote ${path}`);
  } else if (!existsSync(full) || readFileSync(full, 'utf8') !== content) {
    errors.push(`${path} is stale — run: node scripts/check-tracker.mjs --write`);
  }
}

// --- Report ---
if (errors.length > 0) {
  console.error(`\ncheck-tracker: ${errors.length} problem(s)\n`);
  for (const e of errors) console.error(`  ✗ ${e}`);
  process.exit(1);
}
console.log(`check-tracker: OK (${tasks.length} task(s), ${bugs.length} bug(s))`);
