import { ConfigForm } from './config-form.js';
import { resolveArtifact } from './session.js';
import { initAccount, onBundleReady, getStoredBundle } from './account.js';

// ── Tab routing ───────────────────────────────────────────────────────────────

function setActiveTab(tabId) {
    document.querySelectorAll('.topnav-tab').forEach(el => {
        el.classList.toggle('active', el.dataset.tab === tabId);
    });
    document.querySelectorAll('.tab-section').forEach(el => {
        el.classList.toggle('active', el.id === `tab-${tabId}`);
    });
}

document.querySelectorAll('.topnav-tab').forEach(btn => {
    btn.addEventListener('click', () => setActiveTab(btn.dataset.tab));
});

// In-page links that jump to a top-nav tab (e.g. the landing "See the full feature list" CTA).
document.querySelectorAll('[data-goto-tab]').forEach(el => {
    el.addEventListener('click', () => setActiveTab(el.dataset.gotoTab));
});

setActiveTab('home');

// ── Features sub-tabs ───────────────────────────────────────────────────────────
function setActiveSubtab(subtabId) {
    document.querySelectorAll('.subtab').forEach(el => {
        el.classList.toggle('active', el.dataset.subtab === subtabId);
    });
    document.querySelectorAll('.subtab-panel').forEach(el => {
        el.classList.toggle('active', el.dataset.subtabPanel === subtabId);
    });
}

document.querySelectorAll('.subtab').forEach(btn => {
    btn.addEventListener('click', () => setActiveSubtab(btn.dataset.subtab));
});

// ── Randomizer wizard ─────────────────────────────────────────────────────────

let currentStep = 1;
let currentConfig = null;
let currentBundle = null;
let currentWorker = null;

const form = new ConfigForm(document.getElementById('config-form-mount'), {
    onConfigChange(cfg) { currentConfig = cfg; },
});
currentConfig = form.getConfig();

function showStep(n) {
    currentStep = n;
    document.querySelectorAll('.wizard-panel').forEach(el => {
        el.classList.toggle('active', el.dataset.step === String(n));
    });
    document.querySelectorAll('.step').forEach(el => {
        const s = parseInt(el.dataset.stepNum, 10);
        el.classList.toggle('active', s === n);
        el.classList.toggle('done', s < n);
    });
}

// Step 1 → 2: Review
document.getElementById('btn-to-review').addEventListener('click', () => {
    currentConfig = form.getConfig();
    if (!currentConfig) { alert('Please check your settings.'); return; }
    renderReview(currentConfig);
    showStep(2);
});

// Step 2 → 1: Back
document.getElementById('btn-back-to-config').addEventListener('click', () => showStep(1));

// Step 2 → 3: Generate — runs the randomizer in a Web Worker (no API call)
document.getElementById('btn-generate').addEventListener('click', () => {
    currentConfig = form.getConfig();
    if (!currentConfig) { alert('Please check your settings.'); return; }

    if (currentConfig.seed == null) {
        currentConfig.seed = (Math.random() * 0xFFFFFFFF) >>> 0;
    }

    showStep(3);
    resetGenerateUI();
    startWorker(currentConfig);
});

// Step 3 → 1: Start over
document.getElementById('btn-start-over').addEventListener('click', () => {
    terminateWorker();
    showStep(1);
});
document.getElementById('btn-start-over-err').addEventListener('click', () => {
    terminateWorker();
    showStep(1);
});

// Sprite map (base64 data URIs) embedded into each doc so the output HTML is
// fully self-contained — no external CDN, no served images (T-001). Generated by
// `node build.js` into frontend/data/sprites.json; fetched once and cached as text
// so it can be inlined verbatim.
let _spriteMapPromise = null;
function loadSpriteMapText() {
    if (!_spriteMapPromise) {
        _spriteMapPromise = fetch('/data/sprites.json').then(r => {
            if (!r.ok) throw new Error('sprites.json not found — run `node build.js`');
            return r.text();
        });
    }
    return _spriteMapPromise;
}

// Static-asset map (fonts/logo/icons as base64 data URIs) embedded into each doc
// for full self-containment (T-004). Generated by `node build.js` into
// frontend/data/assets.json; fetched once and cached as text.
let _assetMapPromise = null;
function loadAssetMapText() {
    if (!_assetMapPromise) {
        _assetMapPromise = fetch('/data/assets.json').then(r => {
            if (!r.ok) throw new Error('assets.json not found — run `node build.js`');
            return r.text();
        });
    }
    return _assetMapPromise;
}

// Level-cap boss data (caps.c × boss↔flag SSOT) embedded into each doc to drive the
// Mail feature (T-007). Generated by `node build.js` into frontend/data/bosscaps.json.
let _bossCapsPromise = null;
function loadBossCapsText() {
    if (!_bossCapsPromise) {
        _bossCapsPromise = fetch('/data/bosscaps.json').then(r => {
            if (!r.ok) throw new Error('bosscaps.json not found — run `node build.js`');
            return r.text();
        });
    }
    return _bossCapsPromise;
}

// Poke fields the docs never render — dropped at injection time to keep the generated
// HTML small. `contextualRatings` alone is ~10 MB (~70% of the doc); the rest are
// internal pipeline data with zero references in template.html (T-004 analysis).
const DOC_OMIT_POKE_FIELDS = new Set([
    'contextualRatings', 'teachableLearnset', 'levelUpLearnset',
    'natDexNum', 'speciesName', 'catchRate', 'expYield',
]);

function slimPokes(pokes) {
    return pokes.map((p) => {
        const out = {};
        for (const k in p) if (!DOC_OMIT_POKE_FIELDS.has(k)) out[k] = p[k];
        return out;
    });
}

// T-005 — per-run localStorage namespace. Mirrors randomizer/writer.js docRunNamespace
// (canonical formula lives there). Baked into each generated doc so docs from different
// runs opened in the same browser/origin never share UI state.
function docRunNamespace(seed, playerIndex, romIndex) {
    const parts = [];
    if (seed !== undefined && seed !== null && String(seed) !== '') parts.push(`s${seed}`);
    if (playerIndex !== undefined && playerIndex !== null) parts.push(`p${playerIndex}`);
    if (romIndex !== undefined && romIndex !== null) parts.push(`r${romIndex}`);
    return parts.join('-').replace(/[^A-Za-z0-9_-]/g, '');
}

// Inline a ROM's data (+ the shared sprite map) into the template, producing a
// fully self-contained doc HTML. Single source for both download paths.
function buildDocHtml(template, rom, pokedex, spritesText, assetsText, seed, bossCapsText) {
    const assets = JSON.parse(assetsText);
    const runNs = docRunNamespace(seed, rom.playerIndex, rom.romIndex);
    return template
        .split('%%DOC_RUN_NS%%').join(runNs)
        .replace('<script src="sprites.js"></script>',
            `<script>const EMBEDDED_SPRITES = ${spritesText};</script>`)
        .replace('<script src="assets.js"></script>',
            `<script>const EMBEDDED_ASSETS = ${assetsText};</script>`)
        .replace('<script src="bosscaps.js"></script>',
            `<script>const bossCaps = ${bossCapsText || '[]'};</script>`)
        .split('__FONT_PRESS_START_2P__').join(assets['fonts/PressStart2P.woff2'] || '')
        .split('__FONT_VT323__').join(assets['fonts/VT323.woff2'] || '')
        .replace('<script src="trainers.js"></script>',
            `<script>const trainersData = ${JSON.stringify(rom.docs.trainersResultsSimplified)};</script>`)
        .replace('<script src="pokes.js"></script>',
            `<script>const pokes = ${JSON.stringify(slimPokes(pokedex.pokes))};</script>`)
        .replace('<script src="moves.js"></script>',
            `<script>const movesData = ${JSON.stringify(pokedex.moves)};</script>`)
        .replace('<script src="abilities.js"></script>',
            `<script>const abilitiesData = ${JSON.stringify(pokedex.abilities)};</script>`)
        .replace('<script src="wildpokes.js"></script>',
            `<script>const wildPokes = ${JSON.stringify(rom.docs.wildPokes)};</script>`);
}

// Download docs (ZIP: per-ROM docs HTML + the run bundle.json)
document.getElementById('btn-download-docs').addEventListener('click', async () => {
    if (!currentBundle) return;

    const btn = document.getElementById('btn-download-docs');
    btn.disabled = true;
    btn.textContent = 'Building ZIP…';

    try {
        const template = await fetch('/template.html').then(r => {
            if (!r.ok) throw new Error('Template not found');
            return r.text();
        });
        const spritesText = await loadSpriteMapText();
        const assetsText = await loadAssetMapText();
        const bossCapsText = await loadBossCapsText();

        const zip = new JSZip();
        zip.file('bundle.json', JSON.stringify(currentBundle, null, 2));

        for (const rom of currentBundle.roms) {
            const pokedex = resolveArtifact(rom.artifacts.pokedex, currentBundle.sharedData, 'pokedex');

            const html = buildDocHtml(template, rom, pokedex, spritesText, assetsText, currentBundle.config?.seed ?? 'unknown', bossCapsText);

            const label = rom.playerIndex !== undefined
                ? `docs/player-${rom.playerIndex}-rom-${rom.romIndex}.html`
                : `docs/rom-${rom.romIndex}.html`;
            zip.file(label, html);
        }

        const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } });
        const seed = currentBundle.config?.seed ?? 'unknown';
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = `run-${seed}.zip`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(a.href);
    } catch (err) {
        alert(`ZIP generation failed: ${err.message}`);
    } finally {
        btn.disabled = false;
        btn.textContent = '⬇ Download docs';
    }
});

// Init
showStep(1);
// T-028/T-031: wire the account modal; on reload with an in-flight build, surface it — the status
// panel lives in step 3 (hidden by default), so jump there and restore the docs from the stored bundle.
initAccount({
    onRecover: async () => {
        try {
            const b = await getStoredBundle();
            if (b) { currentBundle = b; currentConfig = b.config || currentConfig; }
        } catch { /* ignore */ }
        setActiveTab('randomizer');
        showStep(3);
        document.getElementById('gen-running').style.display = 'none';
        document.getElementById('gen-error').style.display = 'none';
        document.getElementById('gen-done').style.display = '';
        document.getElementById('gen-done-meta').textContent = currentBundle
            ? 'Picked up your in-flight run — your ROM status is below.'
            : 'You have a build in progress — status below.';
        // account.js fills the ROM checklist row + manages the Download buttons.
    },
});

// ── Web Worker helpers ────────────────────────────────────────────────────────

function startWorker(config) {
    terminateWorker();
    _realPct = 0;
    _displayPct = 0;
    startCrawl();

    const worker = new Worker('/js/randomizer.bundle.js');
    currentWorker = worker;

    worker.onmessage = ({ data }) => {
        if (data.type === 'progress') {
            updateProgressUI(data.pct, data.step);
        } else if (data.type === 'done') {
            stopCrawl();
            currentBundle = data.bundle;
            worker.terminate();
            currentWorker = null;
            showGenDone();
        } else if (data.type === 'error') {
            stopCrawl();
            worker.terminate();
            currentWorker = null;
            showGenError(data.message);
        }
    };

    worker.onerror = (e) => {
        stopCrawl();
        worker.terminate();
        currentWorker = null;
        showGenError(e.message || 'Worker crashed.');
    };

    worker.postMessage({ type: 'generate', config });
}

function terminateWorker() {
    stopCrawl();
    if (currentWorker) { currentWorker.terminate(); currentWorker = null; }
}

// ── Progress crawl animation ──────────────────────────────────────────────────

let _crawlInterval = null;
let _realPct = 0;
let _displayPct = 0;

function startCrawl() {
    stopCrawl();
    _crawlInterval = setInterval(() => {
        const ceiling = Math.min(_realPct + 18, 95);
        if (_displayPct < ceiling) {
            _displayPct = Math.min(_displayPct + 0.25, ceiling);
            _setBarUI(Math.round(_displayPct));
        }
    }, 250);
}

function stopCrawl() {
    if (_crawlInterval) { clearInterval(_crawlInterval); _crawlInterval = null; }
}

// ── Step 3 UI states ──────────────────────────────────────────────────────────

function resetGenerateUI() {
    _realPct = 0;
    _displayPct = 0;
    document.getElementById('gen-running').style.display = '';
    document.getElementById('gen-done').style.display    = 'none';
    document.getElementById('gen-error').style.display   = 'none';
    _setBarUI(0);
    document.getElementById('gen-step-label').textContent = 'Starting…';
}

function _setBarUI(pct) {
    document.getElementById('gen-progress-fill').style.width = `${pct}%`;
    document.getElementById('gen-progress-pct').textContent  = `${pct}%`;
}

function updateProgressUI(pct, step) {
    _realPct = pct;
    if (pct > _displayPct) _displayPct = pct;
    _setBarUI(Math.round(_displayPct));
    document.getElementById('gen-step-label').textContent = step;
}

function showGenDone() {
    document.getElementById('gen-running').style.display = 'none';
    document.getElementById('gen-done').style.display    = '';

    const cfg = currentConfig ?? {};
    const numROMs = cfg.runType === 'default' ? 1
        : cfg.runType === 'nuzlocke' ? cfg.numROMs
        : (cfg.numPlayers ?? 1) * (cfg.romsPerPlayer ?? 1);

    document.getElementById('gen-done-meta').textContent =
        `Seed ${cfg.seed} · ${numROMs} ROM${numROMs !== 1 ? 's' : ''}`;

    // T-028: docs are ready (download button is always available); kick off the ROM build if the
    // user is eligible and let account.js drive the ROM checklist row + the Download ROM button.
    onBundleReady(currentBundle);
}

function showGenError(message) {
    document.getElementById('gen-running').style.display = 'none';
    document.getElementById('gen-error').style.display   = '';
    document.getElementById('gen-error-msg').textContent = message;
}

// ── Review renderer ───────────────────────────────────────────────────────────

function fmtShared(shared) {
    const parts = [];
    if (shared.pokedex)  parts.push('Pokémon universe');
    if (shared.trainers) parts.push('trainer teams & rewards');
    if (shared.starters) parts.push('starters');
    return parts.length > 0 ? parts.join(', ') : 'none';
}

function renderReview(cfg) {
    const rows = [];

    if (cfg.runType === 'default') {
        rows.push(['Run type', 'Default']);
        rows.push(['ROMs', '1']);
    } else if (cfg.runType === 'nuzlocke') {
        rows.push(['Run type', 'Nuzlocke']);
        rows.push(['Number of ROMs', cfg.numROMs]);
        rows.push(['Shared', fmtShared(cfg.shared)]);
    } else if (cfg.runType === 'soullink') {
        rows.push(['Run type', 'Soul-Link']);
        rows.push(['Players', cfg.numPlayers]);
        rows.push(['ROMs per player', cfg.romsPerPlayer]);
        rows.push(['Total ROMs', cfg.numPlayers * cfg.romsPerPlayer]);
        rows.push(['Players share', fmtShared(cfg.playerShared)]);
        rows.push(['ROM sharing', fmtShared(cfg.romShared)]);
    }

    rows.push(['Difficulty',      String(cfg.difficulty)]);
    rows.push(['Rebalance stats', cfg.rebalance ? 'Yes' : 'No']);
    if (cfg.rebalance) rows.push(['Balance chance', Math.round(cfg.balanceChance * 100) + '%']);
    rows.push(['Seed', cfg.seed != null ? cfg.seed : '(random — assigned on Generate)']);

    document.getElementById('review-rows').innerHTML = rows.map(([k, v]) => `
        <div class="summary-row">
            <span class="summary-key">${k}</span>
            <span class="summary-val">${v}</span>
        </div>
    `).join('');
}
