#include "global.h"
#include "event_data.h"
#include "sound.h"                 // PlayCry_Script
#include "script_pokemon_util.h"   // CreateScriptedWildMon
#include "constants/items.h"
#include "constants/species.h"
#include "constants/sound.h"       // CRY_MODE_ENCOUNTER
#include "randomizer_rewards.h"

// T-235 / ADR-022 — see randomizer_rewards.h. Defaults are SPECIES_NONE/ITEM_NONE (the base gyms used
// GYM_REWARD_MON = SPECIES_NONE). The randomizer regenerates the entries between the anchor comments at
// build time (randomizer/writer.js); the injector overwrites gGymRewards[] at its .map offset. The array
// is read with a runtime index (GetGymReward), so LTO cannot fold it.
const struct GymReward gGymRewards[GYM_REWARD_COUNT] = {
    // @GYM_REWARDS_START (regenerated by writer.js — do not hand-edit between the anchors)
    [GYM_REWARD_RUSTBORO]          = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_DEWFORD]           = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_MAUVILLE]          = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_LAVARIDGE]         = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_PETALBURG]         = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_FORTREE]           = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_MOSSDEEP]          = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_SOOTOPOLIS]        = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_SLATEPORT_MUSEUM]  = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_WEATHER_INSTITUTE] = { SPECIES_NONE, ITEM_NONE },
    [GYM_REWARD_LILYCOVE]          = { SPECIES_NONE, ITEM_NONE },
    // @GYM_REWARDS_END
};

void GetGymReward(void)
{
    u16 index = gSpecialVar_0x8004;
    if (index >= GYM_REWARD_COUNT)
    {
        gSpecialVar_Result = SPECIES_NONE;
        gSpecialVar_0x8005 = ITEM_NONE;
        return;
    }
    gSpecialVar_Result = gGymRewards[index].species;
    gSpecialVar_0x8005 = gGymRewards[index].item;
}

// T-235 — static legendary encounters. Defaults are the base species/levels (regi/mew real; legends NONE,
// matching #define SPECIES_LEGEND1..3 = SPECIES_NONE); the randomizer regenerates the entries between the
// anchors at build time (writer.js). The injector overwrites gStaticEncounters[] at its .map offset.
const struct StaticEncounter gStaticEncounters[STATIC_ENCOUNTER_COUNT] = {
    // @STATIC_ENCOUNTERS_START (regenerated by writer.js — do not hand-edit between the anchors)
    [STATIC_ENCOUNTER_REGIROCK]  = { SPECIES_REGIROCK,  36 },
    [STATIC_ENCOUNTER_REGICE]    = { SPECIES_REGICE,    39 },
    [STATIC_ENCOUNTER_REGISTEEL] = { SPECIES_REGISTEEL, 46 },
    [STATIC_ENCOUNTER_MEW]       = { SPECIES_MEW,       39 },
    [STATIC_ENCOUNTER_LEGEND1]   = { SPECIES_NONE,      61 },
    [STATIC_ENCOUNTER_LEGEND2]   = { SPECIES_NONE,      61 },
    [STATIC_ENCOUNTER_LEGEND3]   = { SPECIES_NONE,      61 },
    // @STATIC_ENCOUNTERS_END
};

// Replaces `playmoncry SPECIES,CRY_MODE_ENCOUNTER` + `setwildbattle SPECIES,level` for a static legendary:
// reads the index from VAR_0x8004, plays the cry and creates the scripted wild mon from gStaticEncounters[].
// A following `waitmoncry` / `special StartRegiBattle` / `special BattleSetup_StartLegendaryBattle` work as
// before (they read gEnemyParty[0]). VAR_RESULT is set to the species for callers that want it.
void SetupStaticEncounter(void)
{
    u16 index = gSpecialVar_0x8004;
    u16 species = (index < STATIC_ENCOUNTER_COUNT) ? gStaticEncounters[index].species : SPECIES_NONE;
    u16 level = (index < STATIC_ENCOUNTER_COUNT) ? gStaticEncounters[index].level : 5;

    PlayCry_Script(species, CRY_MODE_ENCOUNTER);
    CreateScriptedWildMon(species, level, ITEM_NONE);
    gSpecialVar_Result = species;
}

// For the "flew away" branch: VAR_0x8004 = index → VAR_RESULT = species, so the script can
// `copyvar VAR_0x8004, VAR_RESULT` before Common_EventScript_LegendaryFlewAway (which buffers the species
// name from VAR_0x8004).
void GetStaticEncounterSpecies(void)
{
    u16 index = gSpecialVar_0x8004;
    gSpecialVar_Result = (index < STATIC_ENCOUNTER_COUNT) ? gStaticEncounters[index].species : SPECIES_NONE;
}
