#include "global.h"
#include "event_data.h"
#include "item.h"                  // CopyItemName, GetItemPocket
#include "party_menu.h"            // ItemIdToBattleMoveId
#include "move.h"                  // GetMoveName
#include "string_util.h"           // StringCopy, StringAppend, gStringVar1
#include "constants/items.h"
#include "constants/item.h"        // POCKET_TM_HM
#include "constants/moves.h"
#include "constants/flags.h"
#include "randomizer_picks.h"

// T-236 / ADR-022 — see randomizer_picks.h. The randomized entries default to ITEM_NONE (the base is
// never played unpatched); randomizer/itemRandomizer.js regenerates the block between the anchor
// comments at build time, and the injector overwrites gItemPicks[] at its .map offset. The array is
// read with runtime indices (GetItemPickItem/BufferItemPickName), so LTO cannot fold it.
const struct ItemPick gItemPicks[PICK_COUNT] = {
    // @ITEM_PICKS_START (regenerated by itemRandomizer.js — do not hand-edit between the anchors)
    [PICK_PETALBURG_PLATES]        = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE104_GEMS]           = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE104_BERRIES]        = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE117_BERRIES]        = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE117_GEMS]           = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE111_BERRIES]        = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE121_ITEMS]          = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE111_ITEMS]          = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE116_GEM]            = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE116_BERRY]          = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE118_ITEMS]          = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE106_BALL]           = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE102_BALL]           = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE117_PLATE]          = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE110_EXTENDER]       = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE111_BALL_A]         = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE111_BALL_C]         = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE115_BALL]           = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE116_BALL]           = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE106_GOOD_ITEM]      = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE116_X_SPECIAL]      = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE118_BARNY_GOOD]     = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE120_ANGELICA_GOOD]  = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE109_GOOD_ITEM]      = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE110_GOOD_ITEM]      = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE110_LUM]            = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE117_EARTHQUAKE]     = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE111_HP_UP]          = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    [PICK_ROUTE114_WYATT_GOOD]     = {{ ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE }},
    // @ITEM_PICKS_END
    // TM picks — static (see constants/randomizer_picks.h): slot order matches each map script's
    // case/finditem order (cross-checked against the old tmRandomizer PICK_LISTS on conversion).
    [PICK_TM_ROUTE104]             = {{ ITEM_TM05, ITEM_TM06, ITEM_TM07, ITEM_NONE }},
    [PICK_TM_ROUTE104_2]           = {{ ITEM_TM08, ITEM_TM09, ITEM_TM10, ITEM_NONE }},
    [PICK_TM_ROUTE106]             = {{ ITEM_TM04, ITEM_TM03, ITEM_TM02, ITEM_NONE }},
    [PICK_TM_ROUTE110]             = {{ ITEM_TM63, ITEM_TM64, ITEM_TM62, ITEM_NONE }},
    [PICK_TM_ROUTE114_CHARLOTTE]   = {{ ITEM_TM13, ITEM_TM15, ITEM_TM14, ITEM_NONE }},
    [PICK_TM_ROUTE114_NOLAN]       = {{ ITEM_TM88, ITEM_TM89, ITEM_TM90, ITEM_NONE }},
    [PICK_TM_ROUTE114_ANGELINA]    = {{ ITEM_TM57, ITEM_TM58, ITEM_TM59, ITEM_TM60 }},
    [PICK_TM_ROUTE111]             = {{ ITEM_TM80, ITEM_TM79, ITEM_TM81, ITEM_NONE }},
    [PICK_TM_ROUTE117_SCREEN]      = {{ ITEM_TM77, ITEM_TM76, ITEM_NONE, ITEM_NONE }},
    [PICK_TM_ROUTE118]             = {{ ITEM_TM34, ITEM_TM33, ITEM_TM35, ITEM_NONE }},
    [PICK_TM_ROUTE118_2]           = {{ ITEM_TM20, ITEM_TM21, ITEM_TM22, ITEM_NONE }},
    [PICK_TM_ROUTE118_3]           = {{ ITEM_TM39, ITEM_TM40, ITEM_TM41, ITEM_NONE }},
    [PICK_TM_ROUTE120]             = {{ ITEM_TM42, ITEM_TM43, ITEM_TM44, ITEM_NONE }},
    [PICK_TM_ROUTE121_2]           = {{ ITEM_TM45, ITEM_TM46, ITEM_TM47, ITEM_NONE }},
    [PICK_TM_ROUTE125]             = {{ ITEM_TM48, ITEM_TM49, ITEM_TM50, ITEM_NONE }},
    [PICK_TM_ROUTE112_STATUS]      = {{ ITEM_TM85, ITEM_TM86, ITEM_TM87, ITEM_NONE }},
    [PICK_TM_ROUTE112_DMG]         = {{ ITEM_TM23, ITEM_TM24, ITEM_TM25, ITEM_NONE }},
    [PICK_TM_ROUTE111_FOCUS]       = {{ ITEM_TM12, ITEM_TM29, ITEM_TM30, ITEM_NONE }},
    [PICK_TM_ROUTE111_WILTON]      = {{ ITEM_TM26, ITEM_TM27, ITEM_TM28, ITEM_NONE }},
    [PICK_TM_ROUTE121]             = {{ ITEM_TM82, ITEM_TM83, ITEM_TM84, ITEM_NONE }},
    [PICK_TM_ROUTE124]             = {{ ITEM_TM36, ITEM_TM37, ITEM_TM38, ITEM_NONE }},
    [PICK_TM_ROUTE109_RICKY]       = {{ ITEM_TM16, ITEM_TM17, ITEM_TM18, ITEM_NONE }},
    [PICK_TM_ROUTE109_HUEY]        = {{ ITEM_TM68, ITEM_TM69, ITEM_TM70, ITEM_NONE }},
    [PICK_TM_ROUTE116_ITEM]        = {{ ITEM_TM65, ITEM_TM66, ITEM_TM67, ITEM_NONE }},
};

static u16 PickItemAt(u16 pickIndex, u16 slot)
{
    if (pickIndex >= PICK_COUNT || slot >= MAX_PICK_ITEMS)
        return ITEM_NONE;
    return gItemPicks[pickIndex].items[slot];
}

void GetItemPickItem(void)
{
    gSpecialVar_Result = PickItemAt(gSpecialVar_0x8004, gSpecialVar_0x8005);
}

static const u8 sText_TMPrefix[] = _("TM ");

void BufferItemPickName(void)
{
    u16 item = PickItemAt(gSpecialVar_0x8004, gSpecialVar_0x8005);

    if (GetItemPocket(item) == POCKET_TM_HM && ItemIdToBattleMoveId(item) != MOVE_NONE)
    {
        // "TM <move>" — resolves through gTMHMItemMoveIds, so labels follow the injected TM table.
        StringCopy(gStringVar1, sText_TMPrefix);
        StringAppend(gStringVar1, GetMoveName(ItemIdToBattleMoveId(item)));
    }
    else
    {
        CopyItemName(item, gStringVar1);
    }
}

// T-236 — see randomizer_picks.h. One entry per randomizer/constants.js MEGA_TRAINERS entry
// (index = id - 1); megaHiddenWriter.js regenerates the block between the anchors at build time,
// the injector overwrites the array at its .map offset. Read via a runtime loop index, not folded.
const u8 gMegaTrainerHidden[MEGA_TRAINER_COUNT] = {
    // @MEGA_HIDDEN_START (regenerated by megaHiddenWriter.js — do not hand-edit between the anchors)
    [0] = FALSE,
    [1] = FALSE,
    [2] = FALSE,
    [3] = FALSE,
    [4] = FALSE,
    [5] = FALSE,
    [6] = FALSE,
    [7] = FALSE,
    [8] = FALSE,
    [9] = FALSE,
    [10] = FALSE,
    [11] = FALSE,
    [12] = FALSE,
    [13] = FALSE,
    [14] = FALSE,
    [15] = FALSE,
    [16] = FALSE,
    [17] = FALSE,
    [18] = FALSE,
    [19] = FALSE,
    [20] = FALSE,
    // @MEGA_HIDDEN_END
};

// The two object_events of each mega: the trainer NPC is identified by its event script, the
// mega-stone ball by its template flag (unique across all maps — checked at conversion, T-236).
extern const u8 Route111_EventScript_Tyron[];
extern const u8 JaggedPass_EventScript_Autumn[];
extern const u8 Route111_EventScript_Celina[];
extern const u8 Route118_EventScript_Chris[];
extern const u8 Route120_EventScript_Robert[];
extern const u8 Route121_EventScript_Bianca[];
extern const u8 MtPyre_2F_EventScript_Leah[];
extern const u8 Route124_EventScript_Lila[];
extern const u8 Route125_EventScript_Tanya[];
extern const u8 Route127_EventScript_Koji[];
extern const u8 Route129_EventScript_Allison[];
extern const u8 Route123_EventScript_Wendy[];
extern const u8 Route123_EventScript_Alberto[];
extern const u8 Route123_EventScript_Cameron[];
extern const u8 Route123_EventScript_Kayley[];
extern const u8 Route123_EventScript_Braxton[];
extern const u8 Route123_EventScript_Violet[];
extern const u8 Route123_EventScript_Jacki[];
extern const u8 Route123_EventScript_Frederick[];
extern const u8 Route123_EventScript_Davis[];
extern const u8 Route123_EventScript_Jonas[];

struct MegaTrainerObjects
{
    const u8 *trainerScript;
    u16 ballFlag;
};

static const struct MegaTrainerObjects sMegaTrainerObjects[MEGA_TRAINER_COUNT] = {
    [0]  = { Route111_EventScript_Tyron,      FLAG_ITEM_ROUTE_111_STONE_1 },
    [1]  = { JaggedPass_EventScript_Autumn,   FLAG_ITEM_JAGGED_PASS_BURN_HEAL },
    [2]  = { Route111_EventScript_Celina,     FLAG_ITEM_ROUTE_111_STONE_2 },
    [3]  = { Route118_EventScript_Chris,      FLAG_ITEM_ROUTE_119_MEGA },
    [4]  = { Route120_EventScript_Robert,     FLAG_ITEM_ROUTE_120_REVIVE },
    [5]  = { Route121_EventScript_Bianca,     FLAG_ITEM_ROUTE_111_STONE_3 },
    [6]  = { MtPyre_2F_EventScript_Leah,      FLAG_ITEM_MT_PYRE_2F_ULTRA_BALL },
    [7]  = { Route124_EventScript_Lila,       FLAG_ITEM_ROUTE_119_COBA },
    [8]  = { Route125_EventScript_Tanya,      FLAG_ITEM_ROUTE_119_ZAP },
    [9]  = { Route127_EventScript_Koji,       FLAG_ITEM_ROUTE_119_SUPER_REPEL },
    [10] = { Route129_EventScript_Allison,    FLAG_ITEM_ROUTE_119_GRASSGEM },
    [11] = { Route123_EventScript_Wendy,      FLAG_ITEM_ROUTE_123_ELIXIR },
    [12] = { Route123_EventScript_Alberto,    FLAG_ITEM_ROUTE_123_REVIVAL_HERB },
    [13] = { Route123_EventScript_Cameron,    FLAG_ITEM_ROUTE_123_PP_UP },
    [14] = { Route123_EventScript_Kayley,     FLAG_ITEM_ROUTE_123_CALCIUM },
    [15] = { Route123_EventScript_Braxton,    FLAG_ITEM_ROUTE_123_ULTRA_BALL },
    [16] = { Route123_EventScript_Violet,     FLAG_ITEM_ROUTE_123_MEGA_17 },
    [17] = { Route123_EventScript_Jacki,      FLAG_ITEM_ROUTE_123_MEGA_18 },
    [18] = { Route123_EventScript_Frederick,  FLAG_ITEM_ROUTE_123_MEGA_19 },
    [19] = { Route123_EventScript_Davis,      FLAG_ITEM_ROUTE_123_MEGA_20 },
    [20] = { Route123_EventScript_Jonas,      FLAG_ITEM_ROUTE_123_MEGA_21 },
};

bool32 RandomizerIsHiddenMegaObject(const struct ObjectEventTemplate *template)
{
    u32 i;

    for (i = 0; i < MEGA_TRAINER_COUNT; i++)
    {
        if (!gMegaTrainerHidden[i])
            continue;
        if (template->script == sMegaTrainerObjects[i].trainerScript)
            return TRUE;
        if (template->flagId == sMegaTrainerObjects[i].ballFlag)
            return TRUE;
    }
    return FALSE;
}
