// T-236 — mega-trainer removal is data-driven: instead of deleting the two object_events from
// map.json (structural, not injectable), the writer fills gMegaTrainerHidden[] in
// src/randomizer_picks.c and the engine skips spawning a hidden mega's trainer NPC + stone ball.
const fs = require('fs');
const {
    genMegaHiddenSection,
    updateMegaHiddenTable,
    MEGA_TRAINER_COUNT,
} = require('../../megaHiddenWriter');

describe('genMegaHiddenSection (T-236)', () => {
    test('emits one line per mega trainer, TRUE only for hidden indices', () => {
        const lines = genMegaHiddenSection([0, 20]).split('\n');
        expect(lines).toHaveLength(MEGA_TRAINER_COUNT);
        expect(MEGA_TRAINER_COUNT).toBe(21);
        expect(lines[0]).toContain('[0] = TRUE');
        expect(lines[1]).toContain('[1] = FALSE');
        expect(lines[20]).toContain('[20] = TRUE');
    });

    test('no hidden megas → all FALSE', () => {
        const section = genMegaHiddenSection([]);
        expect(section).not.toContain('TRUE');
    });

    test('rejects out-of-range indices', () => {
        expect(() => genMegaHiddenSection([21])).toThrow(/21/);
        expect(() => genMegaHiddenSection([-1])).toThrow(/-1/);
    });
});

describe('updateMegaHiddenTable (T-236)', () => {
    const FILE =
        'const u8 gMegaTrainerHidden[MEGA_TRAINER_COUNT] = {\n' +
        '    // @MEGA_HIDDEN_START (regenerated by megaHiddenWriter.js — do not hand-edit)\n' +
        '    [0] = FALSE,\n' +
        '    // @MEGA_HIDDEN_END\n' +
        '};\n';

    test('regenerates the anchored block', () => {
        const origRead = fs.readFileSync;
        const origWrite = fs.writeFileSync;
        let written = null;
        fs.readFileSync = () => FILE;
        fs.writeFileSync = (p, content) => { written = { p: String(p), content }; };
        try { updateMegaHiddenTable([3]); } finally {
            fs.readFileSync = origRead;
            fs.writeFileSync = origWrite;
        }
        expect(written.p).toContain('randomizer_picks.c');
        expect(written.content).toContain('[3] = TRUE');
        expect(written.content).toContain('@MEGA_HIDDEN_START');
        expect(written.content).toContain('@MEGA_HIDDEN_END');
        const lines = written.content.split('\n').filter(l => /\[\d+\] = (TRUE|FALSE)/.test(l));
        expect(lines).toHaveLength(MEGA_TRAINER_COUNT);
    });
});
